/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface GenerateAnchorReq {
  secrets: Array<SecretDto>
}

export interface GenerateAnchorRes {
  anchor: Array<string>
}

export interface GenerateProofReq {
  pkPath: string
  jwts: Array<string>
  pkOps: Array<string>
  /** 예: merkle path를 레벨별 string 배열로 표현한다면 Vec<Vec<String>> */
  mp: Array<Array<string>>
  /** JS number는 안전정수 범위가 있으니 보통 u32/u64 권장 */
  leafIndex: Array<number>
  root: string
  anchorParts: Array<string>
  hSignUserop: string
  blockTimestamp: string
  random: string
  audList: Array<string>
}

export interface GenerateProofRes {
  result: Array<ProofBundle>
}

export declare function napiGenerateAnchor(req: GenerateAnchorReq): GenerateAnchorRes

export declare function napiGenerateProof(req: GenerateProofReq): GenerateProofRes

export declare function plus100(input: number): number

export interface ProofBundle {
  proof: Array<string>
  publicInputs: Array<string>
}

export interface SecretDto {
  aud: string
  iss: string
  sub: string
}
