[alias]
setup = "test --release --test light_weight test_groth16_setup --features print-trace -- --nocapture"
prove-verify-opt = "test --release --test light_weight test_prove_and_verify --features print-trace,use-optimized -- --nocapture"
prove-verify = "test --release --test light_weight test_prove_and_verify --features print-trace -- --nocapture"
prove-verify-debug = "test --release --test light_weight test_prove_and_verify --features print-trace,constraints-logging -- --nocapture"
prove-verify-opt-debug = "test --release --test light_weight test_prove_and_verify --features print-trace,use-optimized,constraints-logging -- --nocapture"
baerae-prove = "test --release --features use-optimized,memory-logging --package test --test snark_v4_test test_generate_baerae_proof_single -- --nocapture"
baerae-setup = "run --release --features baerae,num-cs-logging --bin generate_baerae_crs -- ./dist"