// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 32599414;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__anchor__frb_create_dl_anchor_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_create_dl_anchor",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req = <crate::dto::anchor::CreateDlAnchorReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::anchor::frb_create_dl_anchor(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__anchor__frb_create_poseidon_anchor_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_create_poseidon_anchor",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req =
                <crate::dto::anchor::CreatePoseidonAnchorReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::anchor::frb_create_poseidon_anchor(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__anchor__frb_dl_derive_indices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_dl_derive_indices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req = <crate::dto::anchor::DlDeriveIndicesReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::anchor::frb_dl_derive_indices(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__proof__frb_generate_proof_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_generate_proof",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req = <crate::dto::proof::GenerateProofReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::proof::frb_generate_proof(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__schnorr__frb_generate_schnorr_signature_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_generate_schnorr_signature",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req =
                <crate::dto::schnorr::GenerateSchnorrSignatureReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::schnorr::frb_generate_schnorr_signature(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__anchor__frb_poseidon_derive_indices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_poseidon_derive_indices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req =
                <crate::dto::anchor::PoseidonDeriveIndicesReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::anchor::frb_poseidon_derive_indices(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__hash__frb_poseidon_hash_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_poseidon_hash",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_req =
                <crate::dto::hash::GeneratePoseidonHashReq>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::hash::frb_poseidon_hash(api_req)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__greet2_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet2",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet2(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::dto::anchor::CreateDlAnchorReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u64>::sse_decode(deserializer);
        let mut var_secrets = <Vec<crate::dto::FfiSecretDto>>::sse_decode(deserializer);
        return crate::dto::anchor::CreateDlAnchorReq {
            handle: var_handle,
            secrets: var_secrets,
        };
    }
}

impl SseDecode for crate::dto::anchor::CreateDlAnchorRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_anchor = <Vec<String>>::sse_decode(deserializer);
        return crate::dto::anchor::CreateDlAnchorRes { anchor: var_anchor };
    }
}

impl SseDecode for crate::dto::anchor::CreatePoseidonAnchorReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_keyPath = <String>::sse_decode(deserializer);
        let mut var_secrets = <Vec<crate::dto::FfiSecretDto>>::sse_decode(deserializer);
        return crate::dto::anchor::CreatePoseidonAnchorReq {
            key_path: var_keyPath,
            secrets: var_secrets,
        };
    }
}

impl SseDecode for crate::dto::anchor::CreatePoseidonAnchorRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_anchor = <Vec<String>>::sse_decode(deserializer);
        return crate::dto::anchor::CreatePoseidonAnchorRes { anchor: var_anchor };
    }
}

impl SseDecode for crate::dto::anchor::DlDeriveIndicesReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u64>::sse_decode(deserializer);
        let mut var_anchor = <Vec<String>>::sse_decode(deserializer);
        let mut var_knownSecrets = <Vec<crate::dto::FfiSecretDto>>::sse_decode(deserializer);
        return crate::dto::anchor::DlDeriveIndicesReq {
            handle: var_handle,
            anchor: var_anchor,
            known_secrets: var_knownSecrets,
        };
    }
}

impl SseDecode for crate::dto::anchor::DlDeriveIndicesRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_indices = <Vec<u8>>::sse_decode(deserializer);
        return crate::dto::anchor::DlDeriveIndicesRes {
            indices: var_indices,
        };
    }
}

impl SseDecode for crate::dto::FfiSecretDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sub = <Option<String>>::sse_decode(deserializer);
        let mut var_iss = <Option<String>>::sse_decode(deserializer);
        let mut var_aud = <Option<String>>::sse_decode(deserializer);
        return crate::dto::FfiSecretDto {
            sub: var_sub,
            iss: var_iss,
            aud: var_aud,
        };
    }
}

impl SseDecode for crate::dto::hash::GeneratePoseidonHashReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputs = <Vec<String>>::sse_decode(deserializer);
        return crate::dto::hash::GeneratePoseidonHashReq { inputs: var_inputs };
    }
}

impl SseDecode for crate::dto::hash::GeneratePoseidonHashRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hash = <String>::sse_decode(deserializer);
        return crate::dto::hash::GeneratePoseidonHashRes { hash: var_hash };
    }
}

impl SseDecode for crate::dto::proof::GenerateProofReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pkPath = <String>::sse_decode(deserializer);
        let mut var_anchorKeyPath = <String>::sse_decode(deserializer);
        let mut var_schnorrKeyPath = <String>::sse_decode(deserializer);
        let mut var_anchorParts = <Vec<String>>::sse_decode(deserializer);
        let mut var_selectedSecrets = <Vec<crate::dto::FfiSecretDto>>::sse_decode(deserializer);
        let mut var_jwts = <Vec<String>>::sse_decode(deserializer);
        let mut var_pks = <Vec<String>>::sse_decode(deserializer);
        let mut var_mps = <Vec<Vec<String>>>::sse_decode(deserializer);
        let mut var_root = <String>::sse_decode(deserializer);
        let mut var_signature = <Vec<u8>>::sse_decode(deserializer);
        let mut var_leafIndex = <Vec<u32>>::sse_decode(deserializer);
        let mut var_selector = <Vec<bool>>::sse_decode(deserializer);
        let mut var_counter = <String>::sse_decode(deserializer);
        let mut var_random = <String>::sse_decode(deserializer);
        let mut var_hUserop = <String>::sse_decode(deserializer);
        let mut var_slot = <Vec<u8>>::sse_decode(deserializer);
        return crate::dto::proof::GenerateProofReq {
            pk_path: var_pkPath,
            anchor_key_path: var_anchorKeyPath,
            schnorr_key_path: var_schnorrKeyPath,
            anchor_parts: var_anchorParts,
            selected_secrets: var_selectedSecrets,
            jwts: var_jwts,
            pks: var_pks,
            mps: var_mps,
            root: var_root,
            signature: var_signature,
            leaf_index: var_leafIndex,
            selector: var_selector,
            counter: var_counter,
            random: var_random,
            h_userop: var_hUserop,
            slot: var_slot,
        };
    }
}

impl SseDecode for crate::dto::proof::GenerateProofRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_proof = <Vec<String>>::sse_decode(deserializer);
        let mut var_publicInputs = <Vec<String>>::sse_decode(deserializer);
        return crate::dto::proof::GenerateProofRes {
            proof: var_proof,
            public_inputs: var_publicInputs,
        };
    }
}

impl SseDecode for crate::dto::schnorr::GenerateSchnorrSignatureReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_schnorrKeyPath = <String>::sse_decode(deserializer);
        let mut var_root = <String>::sse_decode(deserializer);
        return crate::dto::schnorr::GenerateSchnorrSignatureReq {
            schnorr_key_path: var_schnorrKeyPath,
            root: var_root,
        };
    }
}

impl SseDecode for crate::dto::schnorr::GenerateSchnorrSignatureRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_signature = <Vec<u8>>::sse_decode(deserializer);
        return crate::dto::schnorr::GenerateSchnorrSignatureRes {
            signature: var_signature,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<bool>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::dto::FfiSecretDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::dto::FfiSecretDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::dto::proof::GenerateProofRes> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::dto::proof::GenerateProofRes>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<Vec<String>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::dto::anchor::PoseidonDeriveIndicesReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_keyPath = <String>::sse_decode(deserializer);
        let mut var_anchor = <Vec<String>>::sse_decode(deserializer);
        let mut var_knownSecrets = <Vec<crate::dto::FfiSecretDto>>::sse_decode(deserializer);
        return crate::dto::anchor::PoseidonDeriveIndicesReq {
            key_path: var_keyPath,
            anchor: var_anchor,
            known_secrets: var_knownSecrets,
        };
    }
}

impl SseDecode for crate::dto::anchor::PoseidonDeriveIndicesRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_indices = <Vec<u8>>::sse_decode(deserializer);
        return crate::dto::anchor::PoseidonDeriveIndicesRes {
            indices: var_indices,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__anchor__frb_create_dl_anchor_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__anchor__frb_create_poseidon_anchor_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => {
            wire__crate__api__anchor__frb_dl_derive_indices_impl(port, ptr, rust_vec_len, data_len)
        }
        4 => wire__crate__api__proof__frb_generate_proof_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__schnorr__frb_generate_schnorr_signature_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__anchor__frb_poseidon_derive_indices_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__hash__frb_poseidon_hash_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        8 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__simple__greet2_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::CreateDlAnchorReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.secrets.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::CreateDlAnchorReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::CreateDlAnchorReq>
    for crate::dto::anchor::CreateDlAnchorReq
{
    fn into_into_dart(self) -> crate::dto::anchor::CreateDlAnchorReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::CreateDlAnchorRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.anchor.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::CreateDlAnchorRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::CreateDlAnchorRes>
    for crate::dto::anchor::CreateDlAnchorRes
{
    fn into_into_dart(self) -> crate::dto::anchor::CreateDlAnchorRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::CreatePoseidonAnchorReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key_path.into_into_dart().into_dart(),
            self.secrets.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::CreatePoseidonAnchorReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::CreatePoseidonAnchorReq>
    for crate::dto::anchor::CreatePoseidonAnchorReq
{
    fn into_into_dart(self) -> crate::dto::anchor::CreatePoseidonAnchorReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::CreatePoseidonAnchorRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.anchor.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::CreatePoseidonAnchorRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::CreatePoseidonAnchorRes>
    for crate::dto::anchor::CreatePoseidonAnchorRes
{
    fn into_into_dart(self) -> crate::dto::anchor::CreatePoseidonAnchorRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::DlDeriveIndicesReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.anchor.into_into_dart().into_dart(),
            self.known_secrets.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::DlDeriveIndicesReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::DlDeriveIndicesReq>
    for crate::dto::anchor::DlDeriveIndicesReq
{
    fn into_into_dart(self) -> crate::dto::anchor::DlDeriveIndicesReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::DlDeriveIndicesRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.indices.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::DlDeriveIndicesRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::DlDeriveIndicesRes>
    for crate::dto::anchor::DlDeriveIndicesRes
{
    fn into_into_dart(self) -> crate::dto::anchor::DlDeriveIndicesRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::FfiSecretDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sub.into_into_dart().into_dart(),
            self.iss.into_into_dart().into_dart(),
            self.aud.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::dto::FfiSecretDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::FfiSecretDto> for crate::dto::FfiSecretDto {
    fn into_into_dart(self) -> crate::dto::FfiSecretDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::hash::GeneratePoseidonHashReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.inputs.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::hash::GeneratePoseidonHashReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::hash::GeneratePoseidonHashReq>
    for crate::dto::hash::GeneratePoseidonHashReq
{
    fn into_into_dart(self) -> crate::dto::hash::GeneratePoseidonHashReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::hash::GeneratePoseidonHashRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.hash.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::hash::GeneratePoseidonHashRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::hash::GeneratePoseidonHashRes>
    for crate::dto::hash::GeneratePoseidonHashRes
{
    fn into_into_dart(self) -> crate::dto::hash::GeneratePoseidonHashRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::proof::GenerateProofReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pk_path.into_into_dart().into_dart(),
            self.anchor_key_path.into_into_dart().into_dart(),
            self.schnorr_key_path.into_into_dart().into_dart(),
            self.anchor_parts.into_into_dart().into_dart(),
            self.selected_secrets.into_into_dart().into_dart(),
            self.jwts.into_into_dart().into_dart(),
            self.pks.into_into_dart().into_dart(),
            self.mps.into_into_dart().into_dart(),
            self.root.into_into_dart().into_dart(),
            self.signature.into_into_dart().into_dart(),
            self.leaf_index.into_into_dart().into_dart(),
            self.selector.into_into_dart().into_dart(),
            self.counter.into_into_dart().into_dart(),
            self.random.into_into_dart().into_dart(),
            self.h_userop.into_into_dart().into_dart(),
            self.slot.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::proof::GenerateProofReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::proof::GenerateProofReq>
    for crate::dto::proof::GenerateProofReq
{
    fn into_into_dart(self) -> crate::dto::proof::GenerateProofReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::proof::GenerateProofRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.proof.into_into_dart().into_dart(),
            self.public_inputs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::proof::GenerateProofRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::proof::GenerateProofRes>
    for crate::dto::proof::GenerateProofRes
{
    fn into_into_dart(self) -> crate::dto::proof::GenerateProofRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::schnorr::GenerateSchnorrSignatureReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.schnorr_key_path.into_into_dart().into_dart(),
            self.root.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::schnorr::GenerateSchnorrSignatureReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::schnorr::GenerateSchnorrSignatureReq>
    for crate::dto::schnorr::GenerateSchnorrSignatureReq
{
    fn into_into_dart(self) -> crate::dto::schnorr::GenerateSchnorrSignatureReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::schnorr::GenerateSchnorrSignatureRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.signature.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::schnorr::GenerateSchnorrSignatureRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::schnorr::GenerateSchnorrSignatureRes>
    for crate::dto::schnorr::GenerateSchnorrSignatureRes
{
    fn into_into_dart(self) -> crate::dto::schnorr::GenerateSchnorrSignatureRes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::PoseidonDeriveIndicesReq {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key_path.into_into_dart().into_dart(),
            self.anchor.into_into_dart().into_dart(),
            self.known_secrets.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::PoseidonDeriveIndicesReq
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::PoseidonDeriveIndicesReq>
    for crate::dto::anchor::PoseidonDeriveIndicesReq
{
    fn into_into_dart(self) -> crate::dto::anchor::PoseidonDeriveIndicesReq {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dto::anchor::PoseidonDeriveIndicesRes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.indices.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dto::anchor::PoseidonDeriveIndicesRes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dto::anchor::PoseidonDeriveIndicesRes>
    for crate::dto::anchor::PoseidonDeriveIndicesRes
{
    fn into_into_dart(self) -> crate::dto::anchor::PoseidonDeriveIndicesRes {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::dto::anchor::CreateDlAnchorReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.handle, serializer);
        <Vec<crate::dto::FfiSecretDto>>::sse_encode(self.secrets, serializer);
    }
}

impl SseEncode for crate::dto::anchor::CreateDlAnchorRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.anchor, serializer);
    }
}

impl SseEncode for crate::dto::anchor::CreatePoseidonAnchorReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key_path, serializer);
        <Vec<crate::dto::FfiSecretDto>>::sse_encode(self.secrets, serializer);
    }
}

impl SseEncode for crate::dto::anchor::CreatePoseidonAnchorRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.anchor, serializer);
    }
}

impl SseEncode for crate::dto::anchor::DlDeriveIndicesReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.handle, serializer);
        <Vec<String>>::sse_encode(self.anchor, serializer);
        <Vec<crate::dto::FfiSecretDto>>::sse_encode(self.known_secrets, serializer);
    }
}

impl SseEncode for crate::dto::anchor::DlDeriveIndicesRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.indices, serializer);
    }
}

impl SseEncode for crate::dto::FfiSecretDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.sub, serializer);
        <Option<String>>::sse_encode(self.iss, serializer);
        <Option<String>>::sse_encode(self.aud, serializer);
    }
}

impl SseEncode for crate::dto::hash::GeneratePoseidonHashReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.inputs, serializer);
    }
}

impl SseEncode for crate::dto::hash::GeneratePoseidonHashRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.hash, serializer);
    }
}

impl SseEncode for crate::dto::proof::GenerateProofReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.pk_path, serializer);
        <String>::sse_encode(self.anchor_key_path, serializer);
        <String>::sse_encode(self.schnorr_key_path, serializer);
        <Vec<String>>::sse_encode(self.anchor_parts, serializer);
        <Vec<crate::dto::FfiSecretDto>>::sse_encode(self.selected_secrets, serializer);
        <Vec<String>>::sse_encode(self.jwts, serializer);
        <Vec<String>>::sse_encode(self.pks, serializer);
        <Vec<Vec<String>>>::sse_encode(self.mps, serializer);
        <String>::sse_encode(self.root, serializer);
        <Vec<u8>>::sse_encode(self.signature, serializer);
        <Vec<u32>>::sse_encode(self.leaf_index, serializer);
        <Vec<bool>>::sse_encode(self.selector, serializer);
        <String>::sse_encode(self.counter, serializer);
        <String>::sse_encode(self.random, serializer);
        <String>::sse_encode(self.h_userop, serializer);
        <Vec<u8>>::sse_encode(self.slot, serializer);
    }
}

impl SseEncode for crate::dto::proof::GenerateProofRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.proof, serializer);
        <Vec<String>>::sse_encode(self.public_inputs, serializer);
    }
}

impl SseEncode for crate::dto::schnorr::GenerateSchnorrSignatureReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.schnorr_key_path, serializer);
        <String>::sse_encode(self.root, serializer);
    }
}

impl SseEncode for crate::dto::schnorr::GenerateSchnorrSignatureRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.signature, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <bool>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::dto::FfiSecretDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::dto::FfiSecretDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::dto::proof::GenerateProofRes> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::dto::proof::GenerateProofRes>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<String>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::dto::anchor::PoseidonDeriveIndicesReq {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key_path, serializer);
        <Vec<String>>::sse_encode(self.anchor, serializer);
        <Vec<crate::dto::FfiSecretDto>>::sse_encode(self.known_secrets, serializer);
    }
}

impl SseEncode for crate::dto::anchor::PoseidonDeriveIndicesRes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.indices, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
